### ISSUE TITLE
assign operator work incorrectly in travis

### ISSUE THREAD

**Issue by sangyx** [arrayfire/arrayfire#2756]
I run the code in my machine correct. But it can't work currectly in travis.
code:
```cpp
inline std::tuple<af::array, af::array, af::array, af::array> train_test_split(af::array & X, af::array & y, float train_size, int random_state=-1, bool shuffle=true)
{
	int m = X.dims(0), n = X.dims(1), p = y.dims(1);
	int train_num = ceil(m * train_size), test_num = m - train_num;
	std::vector<int> idx(m);
	std::iota(idx.begin(), idx.end(), 0);

	if(shuffle)
		std::shuffle(idx.begin(), idx.end(), std::default_random_engine(random_state));

	af::array X_train(train_num, n), y_train(train_num, p), X_test(test_num, n), y_test(test_num, p);
	for(int i = 0; i < train_num; ++i)
	{
		X_train.row(i) = X.row(idx[i]);
		y_train.row(i) = y.row(idx[i]);
		af_print(X_train.row(i));
		af_print(X.row(idx[i]));
	}

	for(int i = train_num; i < m; ++i)
	{
		X_test.row(i-train_num) = X.row(idx[i]);
		y_test.row(i-train_num) = y.row(idx[i]);
	}

	return std::make_tuple(X_train, y_train, X_test, y_test);
}
``` 

the output is:
```
X_train.row(i)
[1 2 1 1]
    0.0000     0.0000 
X.row(idx[i])
[1 2 1 1]
    1.1966     4.9519 
X_train.row(i)
[1 2 1 1]
    1.6953     0.0000 
X.row(idx[i])
[1 2 1 1]
    1.1768     3.1670 
X_train.row(i)
[1 2 1 1]
    0.0000     0.0000 
X.row(idx[i])
[1 2 1 1]
   -1.0766    -3.1819 
```

.travis.yml
```
language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=bionic
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: &precise_latest_boost_packages
            - gcc-7
            - g++-7
            - build-essential
            - libfreeimage-dev
            - cmake-curses-gui
            - libopenblas-dev
            - libfftw3-dev
            - liblapacke-dev
            - libboost-all-dev
            - lcov
            - libgtest-dev
            - cmake

# before_install:
#     # Combine global build options with OS/compiler-dependent options
#     - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
#     - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo pip install codecov

    - mkdir -p ${DEPS_DIR}/arrayfire
    - wget https://arrayfire.s3.amazonaws.com/3.6.4/ArrayFire-v3.6.4_Linux_x86_64.sh -O /${DEPS_DIR}/ArrayFire-v3.6.4_Linux_x86_64.sh
    - sudo sh ${DEPS_DIR}/ArrayFire-v3.6.4_Linux_x86_64.sh --include-subdir --prefix=/opt
    - sudo sh -c "echo /opt/arrayfire/lib64 > /etc/ld.so.conf.d/arrayfire.conf"
    - sudo ldconfig

    - cd /usr/src/gtest
    - sudo mkdir build
    - cd build/
    - sudo cmake ..
    - sudo make
    - sudo cp libgtest*.a /usr/local/lib
    - cd ${TRAVIS_BUILD_DIR}

script:
    ############################################################################
    # Build main and tests
    ############################################################################
      - sudo mkdir -p build
      - sudo mkdir -p bin
      - cd build
      - sudo cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON -DBUILD_CUDA=OFF ..
      - sudo make MLKIT_TEST_COV
```
